Update disassemble.md
VzBoT3D/docs pull request #105
Opened 2023-10-11 20:09 UTC by tehmaze

Elaborated on replacing the PLA parts as per issue #91

2023-10-11 20:12 UTC, HumbleDeer requested changes
All that remains would be to copy these changes to the other manuals that have a disassembly/replacement step in them. 

Willing to do this myself too, no big deal.

2023-10-11 20:12 UTC, HumbleDeer commented on docs/vz330_mellow/gantry/disassemble.md
> +parts with a different material that can withstand higher temperatures. Te PLA parts may warp
typo here :)
te -> the

2023-10-11 20:14 UTC, HumbleDeer commented on docs/vz330_mellow/gantry/disassemble.md
> +parts with a different material that can withstand higher temperatures. Te PLA parts may warp
Oh -- Having the artificial line length limits isn't really required for our use cases. Any particular reason for using them? 't makes the diff look funny :^)

2023-10-11 21:32 UTC, tehmaze commented
> All that remains would be to copy these changes to the other manuals that have a disassembly/replacement step in them.

Can we make that a snippet that can be recycled in other places?

2023-10-11 21:42 UTC, HumbleDeer commented
> > All that remains would be to copy these changes to the other manuals that have a disassembly/replacement step in them.
> 
> Can we make that a snippet that can be recycled in other places?

yesn't.

Using our system it's not worth doing that. We're better off keeping track of where we have these things posted by having the same stuff posted on the same pages with the same titles.

2023-10-11 22:30 UTC, HumbleDeer approved these changes
It's not ideal, but we can revise this later on or in the future. It's a start! I'll let you decide whether you want to merge this in or wait and polish it up a little more.

2023-10-12 02:44 UTC, HumbleDeer commented
Please see https://github.com/tehmaze-labs/vzbot-docs/pull/2 before merging this PR

2023-10-12 08:45 UTC, merged