Printer config fixes
VzBoT3D/docs pull request #76
Opened 2023-09-15 22:37 UTC by HumbleDeer

Fixes #68 ("Printer configs are wrong / links broken")
Incorporates #75 ("updated the the link to 330AWD-printer.cfg")

2023-09-19 20:40 UTC, HumbleDeer commented
Checked for other broken links, and all seems fine for now.

2023-09-21 16:42 UTC, HumbleDeer commented
Added commits from https://github.com/VzBoT3D/docs/tree/pbsuper-patch-1 to this branch and PR

2023-09-21 16:45 UTC, HumbleDeer commented on docs/assets/images/manual/vz330_mellow/electronics/Printer_config/printer.cfg
> +control: pid
These values use `pid_xx: value` while the ones below use `pid_xx=value`. I assume this is not correct?

2023-09-21 18:21 UTC, HumbleDeer commented
Test deployment succeeds

Ready to merge. I'll do the other fixes in another PR?

2023-10-02 13:46 UTC, pbsuper requested changes
Printer.cfg doesn't match wiring diagrams.

2023-10-02 13:46 UTC, HumbleDeer commented
I... edited the wiring diagram to match the configs.

2023-10-02 14:13 UTC, pbsuper approved these changes
good.

2023-10-02 14:31 UTC, merged